### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by FranklinChen** [justinwoo/purescript-0.12.0-hello-world#1]
Add Travis CI build.

**Comment by justinwoo** [comment]
The README section on "installation" should give an idea of how to start: https://github.com/justinwoo/purescript-0.12.0-hello-world#installation

**Comment by FranklinChen** [comment]
I'm waiting on https://github.com/purescript-contrib/node-purescript/pull/58 before retrying my Travis setup that wants to install PureScript 0.12.0.

**Comment by justinwoo** [comment]
Fixed by #2
